spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/excuse-me
    username: root
    password: mysql

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false

  flyway:
    enabled: true
    url: jdbc:mysql://localhost:3308/excuse-me
    user: root
    password: mysql

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

management:
  endpoint:
    health:
      show-components: always
  endpoints:
    web:
      exposure:
        include: health
